-- Ejecutar TODO este archivo en Supabase > SQL Editor.
-- La aplicación usa la service_role key desde Streamlit Secrets.
-- No publiques nunca esa key en GitHub.

create extension if not exists pgcrypto;

create table if not exists public.registros_diarios (
  id bigint generated by default as identity primary key,
  fecha date not null unique,
  retrasos_horas numeric(12,2) not null default 0,
  depreciacion numeric(14,2) not null default 0,
  sueldo_promedio numeric(14,2) not null default 0,
  altas integer not null default 0,
  bajas integer not null default 0,
  cambios numeric(12,2) not null default 0,
  riesgo_bajo integer not null default 0,
  riesgo_medio integer not null default 0,
  riesgo_alto integer not null default 0,
  observaciones text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.actividades (
  id bigint generated by default as identity primary key,
  fecha date not null,
  codigo text not null default '',
  descripcion text not null default '',
  responsable text not null default '',
  participante text not null default '',
  dias numeric(12,2) not null default 0,
  horas numeric(12,2) not null default 0,
  mano_obra numeric(14,2) not null default 0,
  insumos numeric(14,2) not null default 0,
  viaticos numeric(14,2) not null default 0,
  depreciacion numeric(14,2) not null default 0,
  gastos_admin numeric(14,2) not null default 0,
  entregable text not null default '',
  observaciones text not null default '',
  estado text not null default 'Planeado',
  avance numeric(5,2) not null default 0,
  costo_total numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists actividades_fecha_idx on public.actividades(fecha);
create index if not exists actividades_estado_idx on public.actividades(estado);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists registros_diarios_updated_at on public.registros_diarios;
create trigger registros_diarios_updated_at
before update on public.registros_diarios
for each row execute function public.set_updated_at();

-- Seguridad: la app utiliza service_role en Streamlit Secrets.
-- Estas tablas no se exponen directamente al cliente público.
alter table public.registros_diarios enable row level security;
alter table public.actividades enable row level security;

-- Sin políticas anon: la service_role puede operar por encima de RLS.
-- Si posteriormente agregamos usuarios de Supabase Auth, se pueden crear políticas por usuario.
